#ifdef __DARGHOS_PVP_SYSTEM__
#ifndef __DARGHOS_CONST__
#define __DARGHOS_CONST__

#define UIDS_START_RANGE 20000
#define STORAGES_START_RANGE 55000

enum BattlegroundStatus
{
	BUILDING_TEAMS = 0,
	PREPARING,
	STARTED,
	FINISHED
};

enum BattlegroundFinishBy
{
	BattlegroundFinishByTime = 0,
	BattlegroundFinishByPoints
};

enum BattlegrondRetValue
{
	BATTLEGROUND_NO_ERROR = 0,
	BATTLEGROUND_CLOSED,
	BATTLEGROUND_CAN_NOT_JOIN,
	BATTLEGROUND_PUT_IN_WAITLIST,
	BATTLEGROUND_PUT_INSIDE,
	BATTLEGROUND_PUT_DIRECTLY,
	BATTLEGROUND_ALREADY_IN_WAITLIST,
	BATTLEGROUND_INFIGHT
};

enum Bg_Teams_t
{
	BATTLEGROUND_TEAM_NONE = 0,
	BATTLEGROUND_TEAM_ONE,
	BATTLEGROUND_TEAM_TWO
};

enum DarghosUids
{
    BATTLEGROUND_TEAM_1_ENTRANCE = UIDS_START_RANGE + 500
    ,BATTLEGROUND_TEAM_2_ENTRANCE
	,BATTLEGROUND_TEAM_1_SPAWN
	,BATTLEGROUND_TEAM_2_SPAWN
};

enum DarghosPlayerStorageIds
{
	DARGHOS_STORAGE_BATTLEGROUND_DESERTER_UNTIL = STORAGES_START_RANGE
};

enum DarghosPvpTypes
{
	PVP_SIMPLE_BATTLEGROUND = 0,
	PVP_ARENA_1X1
};

#endif
#endif
