FROM mysql:8.0

# Create custom MySQL configuration file for native password authentication
# This is compatible with older clients (like MariaDB client library used by TFS)
RUN echo "[mysqld]" > /etc/mysql/conf.d/darghos.cnf && \
    echo "default-authentication-plugin=mysql_native_password" >> /etc/mysql/conf.d/darghos.cnf && \
    echo "bind-address=0.0.0.0" >> /etc/mysql/conf.d/darghos.cnf

# Don't copy SQL file - we'll import manually after container starts
# This prevents initialization timeout issues with large SQL files
