-- INCLUDES
dofile(getDataDir() .. "lib/darghos/const.lua")
dofile(getDataDir() .. "lib/darghos/configs.lua")
dofile(getDataDir() .. "lib/darghos/stages.lua")
dofile(getDataDir() .. "lib/darghos/compat.lua")
dofile(getDataDir() .. "lib/darghos/aids.lua")
dofile(getDataDir() .. "lib/darghos/sids.lua")
dofile(getDataDir() .. "lib/darghos/uids.lua")
dofile(getDataDir() .. "lib/darghos/functions.lua")
dofile(getDataDir() .. "lib/darghos/mcord.lua")
dofile(getDataDir() .. "lib/darghos/gids.lua")
dofile(getDataDir() .. "lib/darghos/polls.lua")
dofile(getDataDir() .. "lib/darghos/luaGlobal.lua")

dofile(getDataDir() .. "lib/darghos/lib_item_shop.lua")
dofile(getDataDir() .. "lib/darghos/lib_auctions.lua")
dofile(getDataDir() .. "lib/darghos/lib_movements.lua")
dofile(getDataDir() .. "lib/darghos/lib_actions.lua")
dofile(getDataDir() .. "lib/darghos/lib_playerhistory.lua")
dofile(getDataDir() .. "lib/darghos/lib_changelog.lua")

dofile(getDataDir() .. "lib/darghos/dungeons.lua")
dofile(getDataDir() .. "lib/darghos/arena.lua")
dofile(getDataDir() .. "lib/darghos/tasks.lua")
--dofile(getDataDir() .. "lib/darghos/daily.lua")
